### ISSUE TITLE
:-1: error: Project ERROR: Unknown module(s) in QT: webkit webkitwidgets

### ISSUE THREAD

**Issue by ShoresOfNowhere** [u-235/kchmviewer#29]
Get this error while trying to build in windows on QT Creator 6.3.1, how can I resolve it?

Otherwise, where can prebuilt windows versions be found?

**Comment by u-235** [comment]
Hi!

You need to configure project to use Qt WebEngine. To do this, in the project properties on the [build steps][1] tab, add `USE_WEBENGINE=1` in the "additional arguments" field.


[1]: https://doc.qt.io/qtcreator/creator-build-settings-qmake.html#qmake-build-steps

**Comment by ShoresOfNowhere** [comment]
I've done it, now the error is 

Project ERROR: Unknown module(s) in QT: webenginewidgets

...

**Comment by u-235** [comment]
It is not enough to build an application with the basic Qt libraries. In [INSTALL.md][1] I have described in detail the general requirements and the build process for Linux. Unfortunately, I can't give detailed instructions on how to build an application on Windows, but you can see how it works in [GitHub Actions][2].

I assume you have installed Qt at least 6.2 and in that case you need to `addons.qtwebengine` `addons.qtwebchannel` `addons.qtpositioning` and `qt5compat`. In either case you need the [libzip][3] library.

[1]: https://github.com/u-235/uchmviewer/blob/master/INSTALL.md
[2]: https://github.com/u-235/uchmviewer/blob/master/.github/workflows/build_tests_windows.yml
[3]: https://github.com/nih-at/libzip
